name: Deploy AFE Application

on:
  workflow_dispatch:
    inputs:
      command:
        description: 'Select the command to run'
        required: true
        default: 'plan'
        type: choice
        options:
          - plan
          - apply
      aws_region:
        description: 'Specify the AWS Region'
        required: true
        default: 'us-east-1'
        type: string
      aws_acccess_key_id:
        description: 'Specify the AWS Access Key ID'
        required: true
        default: 'replace_with_your_access_key_id'
        type: string
      aws_secret_access_key:
        description: 'Specify the AWS Secret Access Key'
        required: true
        default: 'replace_with_your_secret_access_key'
        type: string
      app_secret:
        description: 'Specify the App Secret'
        required: true
        default: 'replace_with_your_app_secret'
        type: string
env:
  AWS_DEFAULT_REGION: ${{ github.event.inputs.aws_region }}
  AWS_ACCESS_KEY_ID: ${{ github.event.inputs.aws_acccess_key_id }}
  AWS_SECRET_ACCESS_KEY: ${{ github.event.inputs.aws_secret_access_key }}
  APP_SECRET: ${{ github.event.inputs.app_secret }}

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Set environment variables based on input
        id: set_env_vars
        run: |
          echo "TF_VAR_ghpat=${{ secrets.BOREHOLE_GH_PAT }}" >> $GITHUB_ENV
          echo "TF_VAR_appsecret=${{ github.event.inputs.app_secret }}" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Terraform commands
        run: |
          cd terraform
          
          # Initialize Terraform
          terraform init
          
          if [ "${{ github.event.inputs.command }}" == "plan" ]; then
            terraform plan 
          fi
          if [ "${{ github.event.inputs.command }}" == "apply" ]; then
            terraform apply -auto-approve
          fi
